version: "3"
services:
  # mysql:
  #   image: mysql:latest
  #   container_name: mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=my-secret-pw
  #   restart: always
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8899:80"
    environment:
      - PMA_ARBITRARY=1

